/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATree: typeof import('ant-design-vue/es')['Tree']
    Breadcrumb: typeof import('./src/components/header/breadcrumb.vue')['default']
    Button: typeof import('./src/components/common/button/button.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Icon: typeof import('./src/components/common/icon/icon.vue')['default']
    Logo: typeof import('./src/components/common/logo.vue')['default']
    MainMenuItem: typeof import('./src/components/menu/mainMenuItem.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/menuItem.vue')['default']
    MenuItemContent: typeof import('./src/components/menu/menuItemContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenuItem: typeof import('./src/components/menu/subMenuItem.vue')['default']
    SvgIcon: typeof import('./src/components/common/icon/src/svgIcon.vue')['default']
    TabsOperator: typeof import('./src/components/header/tabs/tabsOperator.vue')['default']
    TabsView: typeof import('./src/components/header/tabs/tabsView.vue')['default']
  }
}
